# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-18 19:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message=b'PAN is not valid', regex=b'[A-Za-z]{5}\\d{4}[A-Za-z]{1}')])),
                ('dob', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EasyReturn Profile',
            },
        ),
    ]
