# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 19:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_auto_20160920_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex=b'\\d{10}')]),
        ),
    ]
