# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-19 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20160920_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
